// flow-typed signature: 306aed384c1688d26f650ec1141847d8
// flow-typed version: <<STUB>>/short-dom_v^1.2.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'short-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'short-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'short-dom/src/create_element' {
  declare module.exports: any;
}

declare module 'short-dom/src/get_element_by_id' {
  declare module.exports: any;
}

declare module 'short-dom/src/get_elements_by_class_name' {
  declare module.exports: any;
}

declare module 'short-dom/src/get_elements_by_tag_name' {
  declare module.exports: any;
}

declare module 'short-dom/src/index' {
  declare module.exports: any;
}

declare module 'short-dom/src/query_selector_all' {
  declare module.exports: any;
}

declare module 'short-dom/src/query_selector' {
  declare module.exports: any;
}

// Filename aliases
declare module 'short-dom/index' {
  declare module.exports: $Exports<'short-dom'>;
}
declare module 'short-dom/index.js' {
  declare module.exports: $Exports<'short-dom'>;
}
declare module 'short-dom/src/create_element.js' {
  declare module.exports: $Exports<'short-dom/src/create_element'>;
}
declare module 'short-dom/src/get_element_by_id.js' {
  declare module.exports: $Exports<'short-dom/src/get_element_by_id'>;
}
declare module 'short-dom/src/get_elements_by_class_name.js' {
  declare module.exports: $Exports<'short-dom/src/get_elements_by_class_name'>;
}
declare module 'short-dom/src/get_elements_by_tag_name.js' {
  declare module.exports: $Exports<'short-dom/src/get_elements_by_tag_name'>;
}
declare module 'short-dom/src/index.js' {
  declare module.exports: $Exports<'short-dom/src/index'>;
}
declare module 'short-dom/src/query_selector_all.js' {
  declare module.exports: $Exports<'short-dom/src/query_selector_all'>;
}
declare module 'short-dom/src/query_selector.js' {
  declare module.exports: $Exports<'short-dom/src/query_selector'>;
}
